# Generated by Django 5.1.3 on 2024-11-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('dados', models.JSONField()),
            ],
        ),
    ]
