# Generated by Django 5.1.3 on 2024-11-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatorio',
            options={'ordering': ['-data_importacao'], 'verbose_name': 'Relatório', 'verbose_name_plural': 'Relatórios'},
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='chave',
            field=models.CharField(db_index=True, help_text='Identificador único do relatório', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='dados',
            field=models.JSONField(help_text='Dados dos chamados em formato JSON'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='data_importacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data e hora da importação'),
        ),
        migrations.AddIndex(
            model_name='relatorio',
            index=models.Index(fields=['data_importacao'], name='relatorios__data_im_0fc3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='relatorio',
            index=models.Index(fields=['chave', 'data_importacao'], name='relatorios__chave_78b1fc_idx'),
        ),
    ]
